### ISSUE TITLE
createMissingFolders option not working. 

### ISSUE THREAD

**Issue by richmondp** [ivan-vesely/gulp-jshint-html-reporter#4]
Hi, 
I tried to generate the report but I got an ENOENT error. Looking at the code it looks like this issue was addressed back in June by adding createMissingFolders but the version in package.json has not been updated. Should this now be at 0.1.3?

**Comment by ivan-vesely** [comment]
@richmondp Yes, I forgot to update in npm repository. 
I just published npm to update npm repository. so it will address your issue. 
Thanks
