### ISSUE TITLE
autoupdate feature

### ISSUE THREAD

**Issue by ailiinov** [ivan-vesely/gulp-jshint-html-reporter#7]
Hi! Nice tool, thanx for your work.
I have a suggestion, my jshint works in watch, starts on every file change, and it would be cool if html page get ability autorefresh by timer.

**Comment by ivan-vesely** [comment]
I don't think it should accommodate autoupdate feature, because to make it autorefresh, it should run up the web server in it, it's getting heavy and out of literal purpose of general reporters.
