### ISSUE TITLE
Output files are not replaced if the module is not reloaded.

### ISSUE THREAD

**Issue by sgen** [ivan-vesely/gulp-jshint-html-reporter#8]
When rerunning gulp-jshint and gulp-jshint-html-reporter on file changes with gulp-watch and deleting the old output files to ensure there are no false reports (#2) the ifs in reporter.js at line 125 (https://github.com/ivan-vesely/gulp-jshint-html-reporter/blob/master/reporter.js#L125) and line 129 (https://github.com/ivan-vesely/gulp-jshint-html-reporter/blob/master/reporter.js#L129) result in no file creation and no output.

**Comment by ivan-vesely** [comment]
Closing with the PR from @sgen
